config/routes.rb
ExamApp::Application.routes.draw do

  resources :teachers
  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/signup',  :to => 'teachers#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => 'sessions#new'

end

app/models/teacher.rb
require 'digest'
class Teacher < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,  :presence => true,
                    :length   => { :maximum => 65, :minimum => 5 }
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }
                       
  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password ==  encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    teacher = find_by_email(email)
    return nil  if teacher.nil?
    return teacher if teacher.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    teacher = find_by_id(id)
    (teacher && teacher.salt == cookie_salt) ? teacher : nil
  end
  
  private
  
    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :signin_filter, :only => :new
  
  def new
  end
  
  def create
    teacher = Teacher.authenticate(params[:session][:email],
                                   params[:session][:password])
    if teacher.nil?
      flash.now[:error] = "Invalid email/password combination!"
      render 'new'
    else
      sign_in teacher
      redirect_back_or teacher
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
  
  private
  
    def signin_filter
      redirect_to teacher_path(current_teacher) if signed_in?
    end
  
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update]
  before_filter :correct_teacher, :only => [:edit, :update]

  def index
  end
  
  def new
    @teacher = Teacher.new
  end
  
  def show
    @teacher = Teacher.find(params[:id])
  end
  
  def edit
  end
  
  def create
    @teacher = Teacher.new(params[:teacher])
    if @teacher.save
      sign_in @teacher
      flash[:success] = "Welcome to the ExamApp!"
      redirect_to @teacher
    else
      render 'new'
    end
  end
  
  def update
    if @teacher.update_attributes(params[:teacher])
      flash[:success] = "Your changes were successfully saved!"
      redirect_to root_path
    else
      render 'edit'
    end
  end
  
  def destroy
  end

  private
  
    def authenticate
      deny_access unless signed_in?
    end
    
    def correct_teacher
      @teacher = Teacher.find(params[:id])
      redirect_to(root_path) unless current_teacher?(@teacher)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(teacher)
    cookies.permanent.signed[:remember_token] = [teacher.id, teacher.salt]
    self.current_teacher = teacher
  end
  
  def current_teacher=(teacher)
    @current_teacher = teacher
  end
  
  def current_teacher
    @current_teacher ||= teacher_from_remember_token
  end
  
  def signed_in?
    !current_teacher.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
    self.current_teacher = nil
  end
  
  def current_teacher?(teacher)
    teacher == current_teacher
  end
  
  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  
  private
  
    def teacher_from_remember_token
      Teacher.authenticate_with_salt(*remember_token)
    end
    
    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
  
    def store_location
      session[:return_to] = request.fullpath
    end
    
    def clear_return_to
      session[:return_to] = nil
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/_header.html.erb
<div class="navbar"><!-- navigation background --></div>
<header>
	<nav class="navigation">
		<ul>
			<li><%= link_to "HOME", root_path %></li>
			<li><%= link_to "HELP", root_path %></li>
			<% if signed_in? %>
			<li><%= link_to "PROFILE", current_teacher %></li>
			<li><%= link_to "SETTINGS", edit_teacher_path(current_teacher) %></li>
			<li><%= link_to "SIGN OUT", signout_path, :method => :delete %></li>
			<% else %>
			<li><%= link_to "ABOUT", root_path %></li>
			<li><%= link_to "TOUR", root_path %></li>
			<li><%= link_to "REGISTER", signup_path %></li>
			<li><%= link_to "SIGN IN", signin_path %></li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExamApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>	
<div class="container">
<% flash.each do |key, value| %>
	<div class="flash <%= key %>"><%= value %></div>
<% end %>	
<%= yield %>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/teachers/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>
<div class="field">
	<%= f.label :email %><br />
	<%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %><br />
  <%= f.password_field :password_confirmation %>
</div>

app/views/teachers/edit.html.erb
<h2>Edit Teacher</h2>

<%= form_for @teacher do |f| %>
	<%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/teachers/new.html.erb
<h2>Sign Up</h2>

<%= form_for @teacher do |f| %>
	<%= render 'fields', :f => f %>
	<div class='actions'>
		<%= f.submit "Sign Up" %>
	</div>
<% end %>

app/views/teachers/show.html.erb
<h2><%= @teacher.name %></h2>